apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: google-map-api
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/jayram0402/Google-Map-API.SpringBoot.git
    targetRevision: HEAD
    path: k8s  
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
